### ISSUE TITLE
Using this with standalone chromedriver remote without Selenium

### ISSUE THREAD

**Issue by andrewvmail** [webdriverio/webdriverrtc#2]
I am getting the error below. Just wondering if this is because I'm not using selenium? I'm just using chromedriver directly with webdriverio (no multiremote).

```
RuntimeError
     Problem: unknown command: wd/hub/session

     Callstack:
     -> init()
```

**Comment by christian-bromann** [comment]
Please retry with the latest published version. Thanks!
